### PR TITLE
Ten Olga

### PR DESCRIPTION
**Pull request by Hashira10**
practice tasks 1,2,3
ID 21B030930

### CODE REVIEW

**Comment by arscool3** [comment]
great, but please check my comments

**Comment by arscool3** [comment]
гуд, 25 / 25

**Comment by Hashira10** [comment]
Some files may be repeated, I did not delete them because they indicate the time of addition to confirm deadlines. Now all practices are in folders

**Comment by arscool3** [comment]
great )
60 / 60

**Pull request closed without merging**
